name: Build and Deploy to Azure

on: push

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: check-into-repo
      uses: actions/checkout@v2
    - name: publish app
      run: dotnet publish -c Release -o app
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with: 
       name: .net-app
       path: app
  deploy:
   runs-on: ubuntu-latest
   permissions:
    id-token: write
   steps:
    - name: login to Azure
      uses: azure/login@v1
      with:
       client-id: ${{secrets.clientId}}
       subscription-id: ${{secrets.subscriptionId}}
       tenant-id: ${{secrets.tenantId}}
    - name: download zip
      uses: actions/download-artifact@v2
      with:
       name: .net-app
    - name: deploy to azure 
      uses: azure/webapps-deploy
      with:
       app-name: swacky
       package: .
    - name: logout from azure
      run: az logout

