name : Build and Deploy a .NET API 
on : push
jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: action/setup-dotnet@v1
      with: 
       dotnet-version: '7.x'

    - name: Publish App
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/app

    - name: Upload Zip
      uses: actions/upload-artifact@v2
      with:
       name: .net-app
       path: ${{env.DOTNET_ROOT}}/app

  deploy:
   needs: build
   runs-on: ubuntu-latest
   permissions:
     id-token: write
   environment:
     name: Production
     url: ${{steps.deploy-to-azure.outputs.webapp-url}}
   steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
       client-id: ${{secrets.clientId}}
       subscription-id: ${{secrets.subscriptionId}}
       tenant-id: ${{secrets.tenantId}}

    - name: Download App
      uses: actions/download-artifact@v2
      with: 
       name: .net-app
       path: .
      
    - name: Upload App 
      id: deploy-to-azure
      uses: azure/web-deploy@v2
      with: 
       app-name: swacky
       package: .

    - name: Azure Logout
      run: az logout
      
  
   
