name: Publish to Azure
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: check in to repo
     uses: actions/checkout@v2
   - name: publish to folder
     run: dotnet publish -c Release -o app
   - name: upload folder as artifact
     uses: actions/upload-artifact@v2
     with:
      name: .net-app
      path: app
 deploy:
  runs-on: ubuntu-latest
  permissions:
   id-token: write
  environment:
   name: Production
   url: ${{steps.deploy.outputs.webapp-url}}
  steps:
   - name: login to Azure
     uses: azure/login@v1
     with:
      client-id: ${{secrets.clientId}}
      subscription-id: ${{secrets.subscriptionId}}
      tenant-id: ${{secrets.tenantId}}
   - name: download artifact
     uses: actions/download-artifact@v2
     with:
      name: .net-app
   - name: upload app to azure
     uses: azure/webapps-deploy@v2
     with: 
      package: .
   - name: logout from azure
     run: az logout
