name: Testing the mic
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: check out repo
     uses: actions/checkout@v2
   - name: publish the app
     run: dotnet publish -c Release -o app
   - name: upload to artifact
     uses: actions/upload-artifact@v2
     with:
      name: .net-app
      path: app
 deploy: 
   needs:  build
   runs-on: ubuntu-latest
   environment: 
    name: Production
    url: ${{steps.deploy-to-azure.outputs.webapp-url}}
   permissions:
    id-token: write
   steps:
    - name: login to azure
      uses: azure/login@v1
      with:
       client-id: ${{secrets.clientId}}
       subscription-id: ${{secrets.subscriptionId}}
       tenant-id: ${{secrets.tenantId}}
    - name: download artifact
      uses: actions/download-artifact@v2
      with: 
       name: .net-app
    - name: upload to azure
      uses: azure/webapps-deploy@v2
      with:
       app-name: swacky
       package: .
    - name: logout
      run: az logout
    
